/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Creation;

import FormatFactory.Converter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import util.JDBCConnector;
import dao.Creation;
import javax.swing.JOptionPane;

/**
 *
 * @author windows
 */
public class PrinterCreation extends javax.swing.JFrame {

    private long last_embid;

    /**
     * Creates new form PrinterCreation
     */
    public PrinterCreation() {
        initComponents();
        last_prno.setText(new Converter().getStringLongValue(getPrinterId()));
    }

    public String getDatefromchooser(Calendar ob) {
        Date d = ob.getTime();
        DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);
        String bthdate = df.format(d);
        return bthdate;
    }

    public long getPrinterId() {
        try {
            Connection con = JDBCConnector.getConnection();
            Statement stmt = con.createStatement();
            String sql = "SELECT Emb_Id FROM dbo.LastPrinterId WHERE Status = 'last'";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                last_embid = rs.getLong("Emb_Id");
            }
        } catch (Exception ex) {
        }
        return last_embid;
    }

    public void setNewPrinterId() {

        long newlastembid = last_embid + 1;

        try {
            Connection con = JDBCConnector.getConnection();
            Statement stmt = con.createStatement();
            String sql = "UPDATE dbo.LastPrinterId SET Emb_Id = '" + newlastembid + "' WHERE Status = 'last'";
            stmt.execute(sql);
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        last_prno = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        embn = new javax.swing.JTextField();
        emb_ad1 = new javax.swing.JTextField();
        emb_ad2 = new javax.swing.JTextField();
        emb_ad3 = new javax.swing.JTextField();
        emb_tp = new javax.swing.JTextField();
        emb_email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Embellishment Plant Creation");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("CREATE EMBELLISHMENT PLANT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 26, 653, 33));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Printer ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 95, 151, 30));

        last_prno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        last_prno.setText("No");
        jPanel1.add(last_prno, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 95, 103, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Embellishment Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 136, 151, 27));

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "              - SELECT CATEGORY-", "Screen Printing", "Heat Seal", "Bonding", "Lacer Cutting", "Pleating", "Embroiding", "Hand Work", "Other" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 136, 231, 27));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Embellishment Plant");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 181, 151, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Address (1)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 230, 151, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Address (2)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 279, 151, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Address (3)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 328, 151, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Telephone Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 377, 151, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Email Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 426, 151, 30));

        embn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        embn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embnActionPerformed(evt);
            }
        });
        jPanel1.add(embn, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 182, 231, 30));

        emb_ad1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emb_ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emb_ad1ActionPerformed(evt);
            }
        });
        jPanel1.add(emb_ad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 231, 231, 30));

        emb_ad2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emb_ad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emb_ad2ActionPerformed(evt);
            }
        });
        jPanel1.add(emb_ad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 280, 231, 30));

        emb_ad3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emb_ad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emb_ad3ActionPerformed(evt);
            }
        });
        jPanel1.add(emb_ad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 329, 231, 30));

        emb_tp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emb_tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emb_tpActionPerformed(evt);
            }
        });
        jPanel1.add(emb_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 378, 231, 30));

        emb_email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emb_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emb_emailActionPerformed(evt);
            }
        });
        jPanel1.add(emb_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 427, 231, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("ADD PRINTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 520, 120, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("CLEAR ALL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 100, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Join Date");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 475, 151, 30));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 475, 231, 30));

        star1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        star1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(star1, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 136, 27, -1));

        star2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        star2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(star2, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 181, 27, -1));

        star3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        star3.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(star3, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 480, 27, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Creation/Hi-Fashion.PNG"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 150, 150));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Creation/Antler.JPG"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 220, 130));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Creation/Screenline.PNG"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 177, 370, 120));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Creation/Sunro.JPG"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 390, 120));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Creation/Tharindu.JPG"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 440, 230, 100));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Creation/Bondville.PNG"))); // NOI18N
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 150, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 879, 560));

        setSize(new java.awt.Dimension(895, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        long pr_id;
        String pr_cat = "";
        String pr_name = "";
        String pr_address1 = "";
        String pr_address2 = "";
        String pr_address3 = "";
        String pr_tel = "";
        String pr_email = "";
        String jdate = "";

        pr_id = new Converter().getLongValue(last_prno.getText());
        pr_cat = jComboBox1.getSelectedItem().toString();
        pr_name = embn.getText().trim();
        pr_address1 = emb_ad1.getText().trim();
        pr_address2 = emb_ad2.getText().trim();
        pr_address3 = emb_ad3.getText().trim();

        pr_email = emb_email.getText().trim().toLowerCase();
        try {
            Calendar c = jDateChooser1.getCalendar();
            jdate = getDatefromchooser(c);
        } catch (Exception ex) {
//            star1.setText("*");
//            star2.setText("*");
//            star3.setText("*");
//            JOptionPane.showMessageDialog(null, "Fill all required fields marks as (*) ");
        }

        while (true) {
            pr_tel = emb_tp.getText().trim();

            if (pr_tel.equals("") || pr_tel.length() == 10) {
                while (true) {
                    if (pr_cat.equals("") || jComboBox1.getSelectedIndex() == 0) {
                        star1.setText("*");
                        star2.setText("*");
                        star3.setText("*");
                        //--------------------------------------------------------------
                        //last_prno.setText("No");
                        jComboBox1.setSelectedIndex(0);
                        embn.setText("");
                        emb_ad1.setText("");
                        emb_ad2.setText("");
                        emb_ad3.setText("");
                        emb_tp.setText("");
                        emb_email.setText("");
                        Date d = new Date();
                        jDateChooser1.setDate(d);
                        //--------------------------------------------------------------
                        JOptionPane.showMessageDialog(null, "Fill all required fields marks as (*) ");
                        break;
                    } else if (pr_name.equals("")) {
                        star1.setText("*");
                        star2.setText("*");
                        star3.setText("*");
                        //--------------------------------------------------------------
                        //last_prno.setText("No");
                        jComboBox1.setSelectedIndex(0);
                        embn.setText("");
                        emb_ad1.setText("");
                        emb_ad2.setText("");
                        emb_ad3.setText("");
                        emb_tp.setText("");
                        emb_email.setText("");
                        Date d = new Date();
                        jDateChooser1.setDate(d);
                        //--------------------------------------------------------------
                        JOptionPane.showMessageDialog(null, "Fill all required fields marks as (*) ");
                        break;
                    } else if (jdate.equals("")) {
                        star1.setText("*");
                        star2.setText("*");
                        star3.setText("*");
                        //--------------------------------------------------------------
                        //last_prno.setText("No");
                        jComboBox1.setSelectedIndex(0);
                        embn.setText("");
                        emb_ad1.setText("");
                        emb_ad2.setText("");
                        emb_ad3.setText("");
                        emb_tp.setText("");
                        emb_email.setText("");
                        Date d = new Date();
                        jDateChooser1.setDate(d);
                        //--------------------------------------------------------------
                        JOptionPane.showMessageDialog(null, "Fill all required fields marks as (*) ");
                        break;
                    } else {
                        Creation cr = new Creation();
                        cr.printerCreate(pr_id, pr_cat, pr_name, pr_address1, pr_address2, pr_address3, pr_tel, pr_email, jdate);
                        setNewPrinterId();
                        //last_prno.setText("No");
                        last_prno.setText(new Converter().getStringLongValue(getPrinterId()));
                        jComboBox1.setSelectedIndex(0);
                        embn.setText("");
                        emb_ad1.setText("");
                        emb_ad2.setText("");
                        emb_ad3.setText("");
                        emb_tp.setText("");
                        emb_email.setText("");
                        Date d = new Date();
                        jDateChooser1.setDate(d);

                        JOptionPane.showMessageDialog(null, "Printer was added successfully");
                        break;
                    }
                }
                break;
            } else {
                JOptionPane.showMessageDialog(null, "Please enter valid telephone number");
                break;
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //last_prno.setText("No");
        jComboBox1.setSelectedIndex(0);
        embn.setText("");
        emb_ad1.setText("");
        emb_ad2.setText("");
        emb_ad3.setText("");
        emb_tp.setText("");
        emb_email.setText("");
        Date d = new Date();
        jDateChooser1.setDate(d);
        star1.setText("*");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        embn.requestFocus();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void embnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embnActionPerformed
        emb_ad1.requestFocus();
    }//GEN-LAST:event_embnActionPerformed

    private void emb_ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emb_ad1ActionPerformed
        emb_ad2.requestFocus();
    }//GEN-LAST:event_emb_ad1ActionPerformed

    private void emb_ad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emb_ad2ActionPerformed
        emb_ad3.requestFocus();
    }//GEN-LAST:event_emb_ad2ActionPerformed

    private void emb_ad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emb_ad3ActionPerformed
        emb_tp.requestFocus();
    }//GEN-LAST:event_emb_ad3ActionPerformed

    private void emb_tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emb_tpActionPerformed
        emb_email.requestFocus();
    }//GEN-LAST:event_emb_tpActionPerformed

    private void emb_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emb_emailActionPerformed
        jDateChooser1.requestFocus();
    }//GEN-LAST:event_emb_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrinterCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrinterCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrinterCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrinterCreation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrinterCreation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emb_ad1;
    private javax.swing.JTextField emb_ad2;
    private javax.swing.JTextField emb_ad3;
    private javax.swing.JTextField emb_email;
    private javax.swing.JTextField emb_tp;
    private javax.swing.JTextField embn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel last_prno;
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    // End of variables declaration//GEN-END:variables
}
